### ISSUE TITLE
WarpDrive Integration

### ISSUE THREAD

**Issue by Bysokar** [StargateMC/GameServer#20]
WarpDrive needs to be modified to support the following;

- [x] Prevent Warping with a stargate active onboard

- [ ] Star Map needs to support the MMOCore Dimension Registry to pull data from to populate the planets and their transition planes ([Reference](https://github.com/StargateMC/MMOCore/tree/master/src/main/java/com/mmocore/module/Dimension))

- [ ] Prevent claiming land using factions inside of a ship's Warp core's configured ship dimensions

- [ ] Prevent Warping between Quadrants in normal space, but allow it in Hyperspace

- [ ] Customised Error messages to fit more within the Stargate hybrid factions server theme

- [ ] Allow a Ship Captain to pilot the ship into claimed land that he or she has build rights in (Factions Integration)

**Comment by Bysokar** [comment]
@LemADEC Sorry to bother you, but are you able to give me any pointers on points 2, 3 and 6? 
Just point me in the right direction if you can please! :)

**Comment by LemADEC** [comment]
I'm pretty sure SGcraft gates need to be closed to allow jumping.

As of current dev version, CelestialObjects need to be defined on both client and server side. Client for rendering the skybox, server for doing the transitions.
The dev version allows to have multiple space and hyperspace dimensions, like separate galaxies or separate star systems depending how your configure it.

The mod already prevents to move a ship in/out of a protected land. To prevent creating a protected land, your protection mod/plugin needs to check the starmap registry which currently as a limited API.

You can have a space area per star system and an hyperspace dimension joining them all. Each area as an enforced world border with a warning range and punishment if you go over it. In theory, several areas can coexist in the same dimension provided they don't overlap through it wasn't tested extensively.

Which errors messages do you have in mind?

There's currently no easy way to know who is 'piloting' the ship. For example an admin ship could have be stolen from a raid or an admin might be helping a player in his ship: when jumping how would I know who's the right pilot in there?
If player A takes player B as a prisoner in a ship stolen from player C, who's permissions should be checked?
Here's several ideas to solve this:
- Option 1: take all players aboard the ship, remove all the ones in creative mode or being OP, then, if the remaining list is greater than 1, use the mod fake player (as currently), otherwise take that player for permission checks.
- Option 2: have a fake player for each ship and register that ship to the clan/faction. That would probably require changing the related plugin so it allows adding fake players and doesn't screw up protection costs.

**Comment by Bysokar** [comment]
@LemADEC  - going over your code relating to celestial objects now, and configuration :) 
Just from what I have been able to gather this is amazing!

Functionally speaking, what we'd probably want is something like this for our server:
![image](https://cloud.githubusercontent.com/assets/9921203/25778038/efe73e66-3335-11e7-869c-cdd10efefca8.png)

I do have a couple of questions though;

- What would be the best way to push the map of dimensions/galaxies into your mod from another, rather than depend on XML?
I've looked at a lot of the code in the dev branch and the methods/fields are protected or private... 
Goal here would be populate the WD mod with entries from MMOCore, just like I'm getting SGCraft to refer to MMOCore for planet locations etc for a more realistic SG experience.

Logically speaking I'd need a way to register/unregister Celestial Objects, and populate all fields (including rendering data and dimensions If they have that).
 
- Is there any problem assigning a planet directly below the hyperspace dimension also? Or does space need to be between them?

**Comment by LemADEC** [comment]
Dimensions are necessarily stacking as Hyperspace > Space > Planet > Planet > etc.
Think of it as having multiple hyperspaces (galaxies), containing multiple spaces (star systems), containing multiple planets.
You can probably hack the configurations to get your double space layer but that doesn't really make sense in terms of lore, will be quite confusing for players and planets won't be visible in the top layers.

You can add or modify XML files then call the new /wreload command.
You can already create you own CelestiaObject with the constructor and add Render data to it.
I can add a CelestiaObjectManager.updateInRegistry() method that will add or replace existing CelestialObjects. You'll not be notified when /wreload is used through.
You'll not be able to add new space/hyperspace dimensions dynamically that way. Those are only registered at boot.

Regarding planes and such, I want to disable them in non-breathing dimensions as it really doesn't make sense to allow atmospheric flight without an atmosphere.

**Comment by Bysokar** [comment]
@LEMADEC Fair enough on all points - but please allow certain ones to work (and perhaps bypass oxygen requirements for those in them?) - eg: Spacecraft.

**Comment by Bysokar** [comment]
@LemADEC Ohhhhhhhhhhh! So hyperspace is above every space dimension, and the config default wasn't referring to the Hyperspace dimension type?

**Comment by LemADEC** [comment]
You can have multiple "trees" of CelestiaObjects.
The root of a tree is always hyperspace.
Objects below hyperspace are always space.
Objects below space are always planets.

**Comment by Bysokar** [comment]
@LemADEC How do you, in theory, travel between Hyperspace trees? Would that require another mod?
PS: I have an idea of how it works now! Thanks :)

**Comment by Bysokar** [comment]
I'm not going to integrate at all with WD, instead I'll be making it not able to warp into claimed land (and rely on shields/weapons for defense).

 I may run with a build that has some of your default messages replaced though, but that's simple as.

PS: I love your work. You've done really well with the latest stuff.

**Comment by LemADEC** [comment]
The idea is to use Jumpgates to switch between galaxies.
The mod license doesn't allow custom binaries redistribution. Your changes need to be server side only or give me more details, or even a pull request to understand what messages are causing the issue.

**Comment by Bysokar** [comment]
Right, that makes sense - doesnt suite out server though. Stargate lore has subspace/ hyperspace as one layer of the entire universe.
We've settled on one space dim per galaxy with planets and whatnot.

As for the license I don't need to modify the client anymore. Server controls the messages sent to players anyway and any custom jump logic (for cancelling) we might need.

Cheers
Bysokar

**Comment by Bysokar** [comment]
Also what exactly is the license you're developing under @LemADEC
